#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff2b;
constexpr uint24_t FX_DATA_BYTES = 50421;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
}

namespace Images
{
  constexpr uint24_t Title = 0x000000;
  constexpr uint24_t PPOT = 0x000C02;
  constexpr uint24_t ClearProgress = 0x003C04;
  constexpr uint24_t Menu = 0x003D50;
  constexpr uint24_t Levels_Select = 0x005B52;
  constexpr uint24_t Levels_Cursor = 0x0071A4;
  constexpr uint24_t Levels_HUD = 0x00733E;
  constexpr uint24_t Levels_Status = 0x009110;
  constexpr uint24_t Levels_Number = 0x009295;
  constexpr uint24_t Levels_NumberOfMoves = 0x0097BF;
  constexpr uint24_t Levels_NumberOfMoves_Numbers = 0x0098D5;
  constexpr uint24_t Puff = 0x00996D;
  constexpr uint24_t Mini_HUD = 0x00B16F;
  constexpr uint24_t Numbers_HUD = 0x00B231;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x00BB93;
}

